// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"Page1":{"path":"Page1","id":"Page1","file":"Page1.jsx"},"Page2":{"path":"Page2","id":"Page2","file":"Page2.jsx"},"index":{"path":"/","id":"index","file":"index.jsx"}},
    routeComponents: {
'Page1': React.lazy(() => import(/* webpackChunkName: "p__Page1" */'../../pages/Page1.jsx')),
'Page2': React.lazy(() => import(/* webpackChunkName: "p__Page2" */'../../pages/Page2.jsx')),
'index': React.lazy(() => import(/* webpackChunkName: "p__index" */'../../pages/index.jsx')),
},
  };
}
